### ISSUE TITLE
404 error when trying to authenticate

### ISSUE THREAD

**Issue by onlymeee** [buoyant/redmine_tweetbook#4]
The plugin seems to have installed OK, but when I click on the Facebook button on the login screen, I'm redirected to <mydomain.com>/auth/facebook, which gives me a 404 error. Same with the Twitter button.

**Comment by buoyant** [comment]
Did you put your keys in settings.yml file.

**Comment by onlymeee** [comment]
Thanks, yes I did.

**Comment by buoyant** [comment]
Did you follow each and every step in readme then can you please paste screenshot of backtrace from your rails  console.

**Comment by onlymeee** [comment]
Hi, the problem seems to be in redmine_tweetbook/apps/views/shared/_tweetbook.html.erb, which creates up to 3 HTML buttons (Twitter, Facebook, Github) linking to URLs such as /auth/facebook that don't exist. There's no rails error; the error I get is an HTML 404 error when I click on one of the buttons, because /auth/facebook etc don't exist. I'm wondering if there's a dependency on something else that needs to be installed to provide authentication services at location /auth/facebook etc?

**Comment by onlymeee** [comment]
This is now resolved, thanks. In redmine/public/.htaccess I had set RackBaseURI to /redmine, so to get it to work I had to change the omniauth path /auth/facebook to /redmine/auth/facebook, etc.
